const vaccineData = [
    {
        vaccineName: "HEXACIMA",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3 , Antigene di superficie dell’epatite B, Polisaccaride dell’Haemophilus influenzae di tipo b (poliribosilribitol fosfato) coniugato alla proteina del tetano",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare), epatite B (rDNA), poliomielite (inattivato) ed Haemophilus influenzae di tipo b (coniugato)",
        dataAutorizzazione: 2013.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus, Epatite B, Haemophilus Influenzae B",
        calendarioVaccinale: "2,4,10 mesi",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario (t0, 2 mesi) + richiamo dopo altri 6 mesi",
        somministrazione: "iniezione intramuscolare faccia antero-laterale della coscia o deltoide se > 15 mesi età"
    },
    {
        vaccineName: "HEXYON",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3 , Antigene di superficie dell’epatite B, Polisaccaride dell’Haemophilus influenzae di tipo b (poliribosilribitol fosfato) coniugato alla proteina del tetano",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare), epatite B (rDNA), poliomielite (inattivato) ed Haemophilus influenzae di tipo b (coniugato)",
        dataAutorizzazione: 2013.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus, Epatite B, Haemophilus Influenzae B",
        calendarioVaccinale: "2,4,10 mesi",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario (t0, 2 mesi) + richiamo dopo altri 6 mesi",
        somministrazione: "iniezione intramuscolare faccia antero-laterale della coscia o deltoide se > 15 mesi età"
    },
    {
        vaccineName: "INFANRIX HEXA",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3 , Antigene di superficie dell’epatite B, Polisaccaride dell’Haemophilus influenzae di tipo b (poliribosilribitol fosfato) coniugato alla proteina del tetano",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare), epatite B (rDNA), poliomielite (inattivato) ed Haemophilus influenzae di tipo b (coniugato)",
        dataAutorizzazione: 2000.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus, Epatite B, Haemophilus Influenzae B",
        calendarioVaccinale: "2,4,10 mesi",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario (t0, 2 mesi) + richiamo dopo altri 6 mesi",
        somministrazione: "iniezione intramuscolare faccia antero-laterale della coscia o deltoide se > 15 mesi età"
    },
    {
        vaccineName: "VAXELIS",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Fimbrie di tipo 2 e 3, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3 , Antigene di superficie dell’epatite B, Polisaccaride dell’Haemophilus influenzae di tipo b (poliribosilribitol fosfato) coniugato alla proteina meningococcica",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare), epatite B (rDNA), poliomielite (inattivato) ed Haemophilus influenzae di tipo b (coniugato)",
        dataAutorizzazione: 2016.0,
        sviluppatori: "MCM vaccine B.V.",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus, Epatite B, Haemophilus Influenzae B",
        calendarioVaccinale: "2,4,10 mesi",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario (t0, 2 mesi) + richiamo dopo altri 6 mesi",
        somministrazione: "iniezione intramuscolare faccia antero-laterale della coscia o deltoide se > 15 mesi età"
    },
    {
        vaccineName: "POLIOBOOSTRIX",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3",
        baseTecnologicaVaccino: "Vaccino (adsorbito, a ridotto contenuto di antigeni) difterico, tetanico, pertossico (componente acellulare) e poliomielitico (inattivato)",
        dataAutorizzazione: 2009.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus",
        calendarioVaccinale: "5,13 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "POLIOINFANRIX",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare) e poliomielite (inattivato)",
        dataAutorizzazione: 2007.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus",
        calendarioVaccinale: "5,13 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "TETRAVAC",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3",
        baseTecnologicaVaccino: "Vaccino coniugato adsorbito contro difterite, tetano, pertosse (componente acellulare) e poliomielite (inattivato)",
        dataAutorizzazione: 2000.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus",
        calendarioVaccinale: "5,13 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "TRIAXIS POLIO",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Fimbrie tipo 2 e 3, Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3",
        baseTecnologicaVaccino: "Vaccino antidifterico, antitetanico, antipertossico (componenti acellulari) e antipoliomielitico (inattivato) (adsorbito, contenuto antigenico ridotto)",
        dataAutorizzazione: 2020.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse, Poliovirus",
        calendarioVaccinale: "5,13 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "BOOSTRIX",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina",
        baseTecnologicaVaccino: "Vaccino (adsorbito, a ridotto contenuto di antigeni) difterico, tetanico e pertossico (componente acellulare)",
        dataAutorizzazione: 2001.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse",
        calendarioVaccinale: "1 dose ogni 10 anni a partire dei 18 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "TRIAXIS",
        antigene: "Tossoide difterico, Tossoide tetanico, Tossoide pertossico, Emoagglutinina filamentosa, Pertactina, Fimbrie di tipo 2 e 3",
        baseTecnologicaVaccino: "Vaccino antidifterico, antitetanico, antipertossico (componenti acellulari) (adsorbito, contenuto antigenico ridotto)",
        dataAutorizzazione: 2016.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse",
        calendarioVaccinale: "1 dose ogni 10 anni a partire dei 18 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "TRIBACCINE",
        antigene: "Tossoide difterico purificato, Tossoide tetanico purificato, Tossoide pertossico purificato",
        baseTecnologicaVaccino: "Vaccino (adsorbito, contenuto antigenico ridotto) antidifterico, antitetanico e antipertossico (componente acellulare)",
        dataAutorizzazione: 2013.0,
        sviluppatori: "AJ Vaccines A/S",
        patologiaDiInteresse: "Difterite, Tetano, Pertosse",
        calendarioVaccinale: "1 dose ogni 10 anni a partire dei 18 anni",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "DIFTETALL",
        antigene: "Tossoide difterico, Tossoide tetanico",
        baseTecnologicaVaccino: "Vaccino antidifterico e antitetanico, adsorbito (a contenuto ridotto di antigene)",
        dataAutorizzazione: 1979.0,
        sviluppatori: "Astro-Pharma GmbH",
        patologiaDiInteresse: "Difterite, Tetano",
        calendarioVaccinale: "preferire dTPa",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "ANATETALL",
        antigene: "Tossoide tetanico purificato",
        baseTecnologicaVaccino: "Vaccino antitetanico adsorbito",
        dataAutorizzazione: 1979.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Tetano",
        calendarioVaccinale: "preferire dTPa",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "IMOVAX TETANO",
        antigene: "Tossoide tetanico purificato",
        baseTecnologicaVaccino: "Vaccino antitetanico adsorbito",
        dataAutorizzazione: 1979.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Tetano",
        calendarioVaccinale: "preferire dTPa",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "IMOVAX POLIO",
        antigene: "Poliovirus (inattivato) tipo 1 ,tipo 2 e tipo 3",
        baseTecnologicaVaccino: "Vaccino a virus inattivato",
        dataAutorizzazione: 1995.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Poliomielite",
        calendarioVaccinale: "preferire esavalente e IPV-dTPa",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "ACT-HIB",
        antigene: "Polisaccaride di Haemophilus influenzae di tipo b coniugato al tossoide tetanico",
        baseTecnologicaVaccino: "Vaccino Haemophilus influenzae di tipo b coniugato al tossoide tetanico",
        dataAutorizzazione: 1994.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Hib",
        calendarioVaccinale: "preferire esavalente",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "HIBERIX",
        antigene: "Polisaccaride di Haemophilus influenzae di tipo b coniugato al tossoide tetanico",
        baseTecnologicaVaccino: "Vaccino Haemophilus influenzae di tipo b coniugato al tossoide tetanico",
        dataAutorizzazione: 1997.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Hib",
        calendarioVaccinale: "preferire esavalente",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "ENGERIX B",
        antigene: "Antigene di superficie dell’epatite B",
        baseTecnologicaVaccino: "Vaccino (rDNA) dell’epatite B, (adsorbito)",
        dataAutorizzazione: 1987.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Epatite B, (ci si può aspettare che prevenga anche epatite D, visto che è un virus opportunista che non infetta se non è presente B)",
        calendarioVaccinale: "preferire esavalente",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "FENDRIX",
        antigene: "Antigene di superficie dell’epatite B",
        baseTecnologicaVaccino: "Vaccino antiepatite B (rDNA) (adiuvato, adsorbito)",
        dataAutorizzazione: 2005.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Epatite B, (ci si può aspettare che prevenga anche epatite D, visto che è un virus opportunista che non infetta se non è presente B)",
        calendarioVaccinale: "preferire esavalente",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "HBVAXPRO",
        antigene: "Antigene di superficie dell’epatite B",
        baseTecnologicaVaccino: "Vaccino antiepatite B (rDNA) (adsorbito)",
        dataAutorizzazione: 2001.0,
        sviluppatori: "Merck Sharp & Dohme B.V.",
        patologiaDiInteresse: "Epatite B, (ci si può aspettare che prevenga anche epatite D, visto che è un virus opportunista che non infetta se non è presente B)",
        calendarioVaccinale: "preferire esavalente",
        obbligatorietà: "Si",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "TWINRIX",
        antigene: "Virus epatite A inattivato, Antigene di superficie dell’epatite B",
        baseTecnologicaVaccino: "Vaccino (adsorbito) antiepatite A (inattivato) ed antiepatite B (rDNA) (adsorbito)",
        dataAutorizzazione: 1996.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Epatite A, Epatite B, (ci si può aspettare che prevenga anche epatite D, visto che è un virus opportunista che non infetta se non è presente B)",
        calendarioVaccinale: "\\",
        obbligatorietà: "Si (epatite B)",
        posologia: "Dose singola",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "AVAXIM",
        antigene: "Virus dell'Epatite A, ceppo GBM (inattivato)",
        baseTecnologicaVaccino: "Vaccino dell’epatite A (inattivato, adsorbito)",
        dataAutorizzazione: 1997.0,
        sviluppatori: "Sanofi Pasteur",
        patologiaDiInteresse: "Epatite A",
        calendarioVaccinale: "\\",
        obbligatorietà: "No",
        posologia: "Dose singola\n Dose singola + richiamo (t0, 6-12 mesi)",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "HAVRIX",
        antigene: "Virus epatite A inattivato",
        baseTecnologicaVaccino: "Vaccino dell’epatite A (inattivato, adsorbito)",
        dataAutorizzazione: 1996.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Epatite A",
        calendarioVaccinale: "\\",
        obbligatorietà: "No",
        posologia: "Dose singola\n Dose singola + richiamo (t0, 6-12 mesi)",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "VAQTA",
        antigene: "Virus dell’epatite A (ceppo CR 326F) (inattivato)",
        baseTecnologicaVaccino: "Vaccino dell’epatite A (inattivato, adsorbito)",
        dataAutorizzazione: 1997.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "Epatite A",
        calendarioVaccinale: "\\",
        obbligatorietà: "No",
        posologia: "Dose singola\n Dose singola + richiamo (t0, 6-12 mesi)",
        somministrazione: "iniezione intramuscolare deltoide"
    },
    {
        vaccineName: "PRIORIX TETRA",
        antigene: "virus vivi attenuati di morbillo, parotite, rosolia e varicella\nvirus del morbillo ceppo Schwarz (vivo, attenuato)\nvirus della parotite ceppo RIT 4385\nvirus della rosolia ceppo Wistar RA 27/3 (vivo, attenuato)\nvirus della varicella ceppo OKA (vivo, attenuato)",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2008.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Morbillo\nParotite\nRosolia\nVaricella\n\n(virus)",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario:\n1 dose tra i 12 e i 15 mesi di età\n2 dose tra 5-6 anni",
        somministrazione: "iniezione per via sottocutanea (SC) o per via intramuscolare (IM), nella regione deltoidea del braccio o nella parte anterolaterale superiore della coscia."
    },
    {
        vaccineName: "PROQUAD",
        antigene: "Virus del morbillo1 ceppo Enders Edmonston\nVirus della parotite1 ceppo Jeryl LynnTM (Livello B) \nVirus della rosolia2 ceppo Wistar RA 27/3\nVirus della varicella3 ceppo Oka/Merck",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2006.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "Morbillo\nParotite\nRosolia\nVaricella\n\n(virus)",
        calendarioVaccinale: "a partire dai 12 mesi di età",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario\n1 dose tra i 12 e i 15 mesi di età\n2 dose tra 5-6 anni",
        somministrazione: "iniezione nel muscolo o sotto la cute nell’area esterna della coscia o nel braccio"
    },
    {
        vaccineName: "MMRVAXPRO",
        antigene: "Virus del morbillo ceppo Enders Edmonston\nVirus della parotite ceppo Jeryl LynnTM (Livello B) \nVirus della rosolia ceppo Wistar RA 27/3",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2006.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "Morbillo\nParotite\nRosolia\n\n(virus)",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario:\n1 dose tra i 12 e i 15 mesi di età\n2 dose tra 5-6 anni",
        somministrazione: "iniezione per via intramuscolare (i.m.) o sottocutanea (s.c.)."
    },
    {
        vaccineName: "PRIORIX",
        antigene: "virus del morbillo vivo attenuato (ceppo Schwarz)\nvirus della parotite vivo attenuato (ceppo RIT 4385, derivato dal ceppo Jeryl Lynn)\nvirus della rosolia vivo attenuato (ceppo Wistar RA 27/3)",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 1998.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Morbillo\nParotite\nRosolia\n\n(virus)",
        calendarioVaccinale: "a partire dai 9 mesi di età \n(1 dose tra i 12 e i 15 mesi di età\n2 dose tra 5-6 anni)",
        obbligatorietà: "Si",
        posologia: "2 dosi ciclo primario:\n1 dose tra i 12 e i 15 mesi di età\n2 dose tra 5-6 anni",
        somministrazione: "somministrazione sottocutanea"
    },
    {
        vaccineName: "VARILRIX",
        antigene: "Virus della varicella ceppo OKA",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 1994.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Varicella\n\n(virus)",
        obbligatorietà: "Si",
        posologia: "2 dosi a distanza di almeno 4 settimane",
        somministrazione: "via sottocutanea (SC) o per via intramuscolare (IM) nella regione deltoidea o nella regione antero-laterale della coscia"
    },
    {
        vaccineName: "VARIVAX",
        antigene: "Virus della varicella ceppo Oka/Merck",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2003.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "Varicella\n\n(virus)",
        obbligatorietà: "Si",
        posologia: "2 dosi a distanza di almeno 4 settimane\n",
        somministrazione: "somministrazione per via intramuscolare (i.m.) o sottocutanea (s.c.)."
    },
    {
        vaccineName: "PNEUMOVAX",
        antigene: "23 sierotipi di polisaccaride pneumococcico: 1, 2, 3, 4, 5, 6B, 7F, 8, 9N, 9V, 10A, 11A, 12F, 14, 15B, 17F, 18C, 19F, 19A, 20, 22F, 23F, 33F.",
        baseTecnologicaVaccino: "vaccino polisaccaridico",
        dataAutorizzazione: 2000.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "Infezione pneumococcica in bambini da 2 anni di età, adolescenti e adulti\nIl vaccino non è efficace nella prevenzione dell’otite media acuta, della sinusite e delle altre infezioni comuni del tratto respiratorio superiore\n\nbatterio Streptococcus pneumoniae",
        obbligatorietà: "No",
        somministrazione: "somministrazione per via intramuscolare (i.m.) o sottocutanea (s.c.)."
    },
    {
        vaccineName: "PREVENAR 13",
        antigene: "Polisaccaride pneumococcico sierotipo1\nPolisaccaride pneumococcico sierotipo 3\nPolisaccaride pneumococcico sierotipo 4\nPolisaccaride pneumococcico sierotipo 5\nPolisaccaride pneumococcico sierotipo 6A \nPolisaccaride pneumococcico sierotipo 6B\nPolisaccaride pneumococcico sierotipo 7F\nPolisaccaride pneumococcico sierotipo 9V\nPolisaccaride pneumococcico sierotipo 14\nPolisaccaride pneumococcico sierotipo 18C\nPolisaccaride pneumococcico sierotipo 19A\nPolisaccaride pneumococcico sierotipo 19F\nPolisaccaride pneumococcico sierotipo 23F\nConiugati alla proteina vettrice CRM197",
        baseTecnologicaVaccino: "vaccino polisaccaridico coniugato (13 valente adsorbito)",
        dataAutorizzazione: 2009.0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "prevenzione di patologia invasiva, polmonite e otite media acuta (OMA), causate da Streptococcus pneumoniae in neonati, bambini e adolescenti di età compresa tra 6 settimane e 17 anni\nprevenzione di patologia invasiva e di polmonite, causata da Streptococcus pneumoniae in adulti di età ≥ di 18 anni e anziani.\n\n\nbatterio Streptocuccus pneumoniae",
        calendarioVaccinale: "età ≥ 6 settimane\nda calendario vaccinale si utilizza in età pediatrica \nnei soggetti a rischio a partire da età  ≥ 2 anni\nnegli adulti si utilizza in combinazione con il polisaccaridico 23-valente",
        obbligatorietà: "No",
        posologia: "3 dosi nel primo anno di vita (3° mese, 5° mese e 11°-13° mese). Se la vaccinazione inizia nel secondo semestre di vita, vanno eseguite ugualmente 3 dosi a distanza di 6-8 settimane l’una dall’altra.\n2 dosi se si inizia dopo il compimento del primo anno o in caso di bambini con condizioni di rischio\n1 dose se si inizia dopo il compimento del secondo anno.",
        somministrazione: "iniezione intramuscolare."
    },
    {
        vaccineName: "SYNFLORIX",
        antigene: "Polisaccaride pneumococcico del sierotipo 1\n Polisaccaride pneumococcico del sierotipo 4\nPolisaccaride pneumococcico del sierotipo 5\nPolisaccaride pneumococcico del sierotipo 6B\nPolisaccaride pneumococcico del sierotipo 7F\nPolisaccaride pneumococcico del sierotipo 9V\nPolisaccaride pneumococcico del sierotipo 14\nPolisaccaride pneumococcico del sierotipo 18\n Polisaccaride pneumococcico del sierotipo 19F\nPolisaccaride pneumococcico del sierotipo 23F\nconiugati a tossoite tetanico/tossoide difterico/proteina D (derivata da Haemophilus influenzae non tipizzabile)",
        baseTecnologicaVaccino: "polisaccaridico coniugato (adsorbito)",
        dataAutorizzazione: 2009.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "patologia invasiva, la polmonite e l’otite media acuta causata da Streptococcus pneumoniae in neonati e bambini da 6 settimane a 5 anni d’età",
        calendarioVaccinale: "da 6 settimane a 5 anni d’età",
        obbligatorietà: "No",
        posologia: "3 dosi nel primo anno di vita (3° mese, 5° mese e 11°-13° mese). Se la vaccinazione inizia nel secondo semestre di vita, vanno eseguite ugualmente 3 dosi a distanza di 6-8 settimane l’una dall’altra.\n2 dosi se si inizia dopo il compimento del primo anno o in caso di bambini con condizioni di rischio\n",
        somministrazione: "iniezione intramuscolare"
    },
    {
        vaccineName: "ROTARIX",
        antigene: "Rotavirus umano ceppo RIX4414",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2006.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "gastroenterite dovuta a infezione da Rotavirus",
        calendarioVaccinale: "lattanti di età compresa tra le 6 e le 24 settimane (Rotarix non deve essere usato in bambini di età superiore alle 24 settimane)",
        obbligatorietà: "No",
        somministrazione: "orale"
    },
    {
        vaccineName: "ROTATEQ",
        antigene: "5 sierotipi di Rotavirus bovino riassortito\nTipo G1 di rotavirus \nTipo G2 di rotavirus \nTipo G3 di rotavirus \nTipo G4 di rotavirus \nTipo* P1A[8] di rotavirus",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2006.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "gastroenterite dovuta a infezione da Rotavirus",
        calendarioVaccinale: "neonati a partire da 6 settimane di età fino alle 32 settimane di età",
        obbligatorietà: "No",
        posologia: "3 dosi a distanza di quattro settimane a partire dalla 6° settimana di vita. La prima dose può essere somministrata a partire dalle 6 settimane di età e non oltre le 12 settimane di età. È preferibile che il ciclo di vaccinazione a tre dosi sia completato entro le 20-22 settimane di età. Se necessario, la terza (ultima) dose può essere somministrata sino alle 32 settimane di età.\nSchedula 3°-5°-7° mese",
        somministrazione: "orale"
    },
    {
        vaccineName: "BEXSERO",
        antigene: "Proteina di fusione ricombinante NHBA di Neisseria meningitidis gruppo B\nProteina ricombinante NadA di Neisseria meningitidis gruppo B\nProteina di fusione ricombinante fHbp di Neisseria meningitidis gruppo B\nVescicole della membrana esterna (OMV) di Neisseria meningitidis gruppo B ceppo NZ98/254 misurate come quantità di proteina totale contenente PorA P1.4",
        baseTecnologicaVaccino: "vaccino ricombinante",
        dataAutorizzazione: 2013.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "malattia meningococcica invasiva causata dal batterio Neisseria meningitidis di gruppo B",
        calendarioVaccinale: "età ≥ 2 anni\n",
        obbligatorietà: "No",
        posologia: "3 dosi + richiamo\n(intervallo tra le dosi primarie di “non meno di 1 mese”, 15 giorni dopo la somministrazione dell'esavalente)\nschedula: 3°-4°-6°+ richiamo al 13° mese\n\nesiste anche la \"schedula inglese\" che prevede 2 dosi primarie + richiamo. si inizia la vaccinazione a 8 settimane con intervallo tra le dosi primarie di “non meno di 2 mesi”, il richiamo al 13° mese",
        somministrazione: "iniezione intramuscolare profonda"
    },
    {
        vaccineName: "TRUMENBA",
        antigene: "fHbp (proteina legante il fattore H) di Neisseria meningitidis sierogruppo B sottofamiglia A\nfHbp (proteina legante il fattore H) di Neisseria meningitidis sierogruppo B sottofamiglia B",
        baseTecnologicaVaccino: "vaccino ricombinante",
        dataAutorizzazione: 2017.0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "malattia meningococcica invasiva causata dal batterio Neisseria meningitidis di gruppo B",
        calendarioVaccinale: "soggetti di età ≥ 10 anni",
        obbligatorietà: "No",
        somministrazione: "iniezione intramuscolare"
    },
    {
        vaccineName: "MENJUGATE",
        antigene: "Oligosaccaride di Neisseria meningitidis gruppo C (ceppo 11): coniugato con Proteina Corynebacterium diphtheriae CRM1971 (Cross Reacting Material 197) ",
        baseTecnologicaVaccino: "vaccino coniugato monovalente",
        dataAutorizzazione: 2015.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "malattia invasiva causata dal batterio Neisseria meningitidis gruppo C",
        calendarioVaccinale: "età ≥ 2 mesi di età (2 dosi fino a 12 mesi di età; dopo i 12 mesi singola dose)\nsecondo il PNPV 17-19 si somministrava 1 dose di antimeningococco C a 12 mesi con Menjugate, seguito da richiamo con vaccino antimeningococco C tetravalente ",
        obbligatorietà: "No",
        posologia: "1 dose + richiamo\n(2 dosi + richiamo se la somministrazione è iniziata prima dei 12 mesi di età)",
        somministrazione: "Iniezione intramuscolare"
    },
    {
        vaccineName: "NEISVAC-C",
        antigene: "polisaccaride (de-O-acetilato) della Neisseria meningitidis gruppo C (ceppo C11) coniugato al tossoide tetanico",
        baseTecnologicaVaccino: "vaccino polisaccaridico coniugato monovalente",
        dataAutorizzazione: 2002.0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "malattia invasiva causata dal batterio Neisseria meningitidis gruppo C",
        calendarioVaccinale: "età ≥ 2 mesi di età",
        obbligatorietà: "No",
        posologia: "1 dose\n(2 dosi ad almeno 2 mesi se età fino a 4 mesi di età)\n1 dose di richiamo nei lattanti e bambini nella prima infanzia di età inferiore a 12 mesi dopo 6 mesi dal completamento della vaccinazione",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "MENVEO",
        antigene: "oligosaccaride del gruppo A meningococcico coniugato alla proteina Corynebacterium diphtheriae CRM197\noligosaccaride del gruppo C meningococcico coniugato alla proteina Corynebacterium diphtheriae CRM197\noligosaccaride del gruppo W-135 meningococcico coniugato alla proteina Corynebacterium diphtheriae CRM197\noligosaccaride del gruppo Y meningococcico coniugato alla proteina Corynebacterium diphtheriae CRM197",
        baseTecnologicaVaccino: "vaccino polisaccaridico coniugato tetravalente ",
        dataAutorizzazione: 2010.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "malattia invasiva causata dal batterio Neisseria meningitidis gruppi A, C, W-135 e Y",
        obbligatorietà: "No",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "NIMENRIX",
        antigene: "Neisseria meningitidis polisaccaride del gruppo A \nNeisseria meningitidis polisaccaride del gruppo C \nNeisseria meningitidis polisaccaride del gruppo W-135 \nNeisseria meningitidis polisaccaride del gruppo Y\n\nconiugate alla proteina vettore del tossoide tetanico",
        baseTecnologicaVaccino: "vaccino polisaccaridico coniugato tetravalente ",
        dataAutorizzazione: 2012.0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "malattia invasiva causata dal batterio Neisseria meningitidis gruppi A, C, W-135 e Y",
        obbligatorietà: "No",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "CERVARIX",
        antigene: "Proteina L1 del Papillomavirus1 umano di tipo 16\nProteina L1 del Papillomavirus1 umano di tipo 18",
        baseTecnologicaVaccino: "vaccino adiuvato ricombinante bivalente",
        dataAutorizzazione: 2007.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "prevenzione delle lesioni ano-genitali precancerose (della cervice uterina, della vulva, della vagina e anali) e del cancro della cervice uterina  e anale causati da determinati Papillomavirus umani (HPV) oncogeni di tipo 16 e 18",
        calendarioVaccinale: "a partire dai 9 anni di età\n\noggi si usa il nonavalente\n",
        obbligatorietà: "No",
        posologia: "2 dosi fino ai 14 anni inclusi di età a distanza di 6 mesi\n3 dosi dai 15 anni di età (0-1,2 mese- 6 mese) da concludere entro l'anno",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "GARDASIL",
        antigene: "Proteina L1 Tipo 6 di Papillomavirus Umano\nProteina L1 Tipo 11 di Papillomavirus Umano \nProteina L1 Tipo 16 di Papillomavirus Umano\nProteina L1 Tipo 18 di Papillomavirus Umano",
        baseTecnologicaVaccino: "vaccino ricombinante quadrivalente",
        dataAutorizzazione: 2006.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "prevenzione delle lesioni ano-genitali precancerose (della cervice uterina, della vulva, della vagina e anali) e del cancro della cervice uterina  e anale causati da determinati Papillomavirus umani (HPV) oncogeni di tipo 6-11-16-18",
        calendarioVaccinale: "a partire dai 9 anni di età\n\noggi si usa il nonavalente\n",
        obbligatorietà: "No",
        posologia: "2 dosi fino a 13 anni di età (0-6 mesi)\nschedula alternativa a 3 dosi (0-2-6 mesi) specie se la 2° dose viene somministrata prima dei 6 mesi dalla prima \n\netà ≥ 14 anni schedula a 3 dosi (0-2-6 mesi)",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "GARDASIL 9",
        antigene: "Proteina L1 Tipo 6 di Papillomavirus Umano\nProteina L1 Tipo 11 di Papillomavirus Umano\nProteina L1 Tipo 16 di Papillomavirus Umano\nProteina L1 Tipo 18 di Papillomavirus Umano\nProteina L1 Tipo 31 di Papillomavirus Umano\nProteina L1 Tipo 33 di Papillomavirus Umano\nProteina L1 Tipo 45 di Papillomavirus Umano\nProteina L1 Tipo 52 di Papillomavirus Umano\nProteina L1 Tipo 58 di Papillomavirus Umano",
        baseTecnologicaVaccino: "vaccino ricombinante nonavalente",
        dataAutorizzazione: 2015.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "prevenzione delle lesioni ano-genitali precancerose (della cervice uterina, della vulva, della vagina e anali) e del cancro della cervice uterina  e anale causati da determinati Papillomavirus umani (HPV) oncogeni di tipo 6-11-16-18-31-33-45-52--58",
        calendarioVaccinale: "a partire dai 9 anni di età",
        obbligatorietà: "No",
        posologia: "2 dosi fino a 14 anni di età (0-6 mesi)\nschedula alternativa a 3 dosi (0-2-6 mesi) specie se la 2° dose viene somministrata prima dei 6 mesi dalla prima \n\netà ≥ 15 anni schedula a 3 dosi (0-2-6 mesi)",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "ZOSTAVAX",
        antigene: "Virus della varicella-zoster1, ceppo Oka/Merck",
        baseTecnologicaVaccino: "vaccino vivo attenuato",
        dataAutorizzazione: 2006.0,
        sviluppatori: "MSD Italia S.r.l.",
        patologiaDiInteresse: "prevenzione dell’herpes zoster (“zoster” o fuoco di S. Antonio) e della nevralgia post-erpetica (post-herpes neuralgia, PHN) associata al virus herpes zoster.\nnon protegge per varicella",
        calendarioVaccinale: "età ≥ 50 anni",
        obbligatorietà: "No",
        posologia: "1 dose",
        somministrazione: "via sottocutanea (s.c.) o intramuscolare (i.m.)"
    },
    {
        vaccineName: "SHINGRIX",
        antigene: "Antigene glicoproteina E del Virus Varicella Zoster",
        baseTecnologicaVaccino: "vaccino ricombinante adiuvato",
        dataAutorizzazione: 2018.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "prevenzione dell’herpes zoster (“zoster” o fuoco di S. Antonio) e della nevralgia post-erpetica (post-herpes neuralgia, PHN) associata al virus herpes zoster.\nnon protegge per varicella",
        calendarioVaccinale: "età ≥ 50 anni\netà ≥ 18 anni ad aumentato rischio di HZ",
        obbligatorietà: "No",
        posologia: "2 dosi (0 - 2,6 mesi)",
        somministrazione: "via intramuscolare"
    },
    {
        vaccineName: "STAMARIL",
        antigene: "• oligosaccaride del gruppo Y meningococcico coniugato alla proteina Corynebacterium diphtheriae CRM197",
        baseTecnologicaVaccino: "vivo attenuato",
        dataAutorizzazione: 2009.0,
        sviluppatori: "Sanofi",
        patologiaDiInteresse: "Febbre gialla, Virus della febbre gialla",
        calendarioVaccinale: "sopra i 6 mesi di età in viaggiatori che si recano in aree a rischio.",
        obbligatorietà: "obbligatorio per l'ingresso in alcuni paesi.",
        posologia: "1 dose",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "TIPHIM VI",
        antigene: "Polisaccaride capsulare purificato ottenuto da Salmonella Typhi (ceppo Ty2)",
        baseTecnologicaVaccino: "vaccino polisacarridico",
        dataAutorizzazione: 2009.0,
        sviluppatori: "Sanofi",
        patologiaDiInteresse: "Tifo, Salmonella Tiphi",
        calendarioVaccinale: "sopra i 6 anni che si recano in aree a rischio",
        obbligatorietà: "no",
        posologia: "1 dose ogni 5 anni se si torna in aree a rischio",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "VOYAPAK",
        antigene: "cellule vitali di Salmonella Typhi Ty21a",
        baseTecnologicaVaccino: "vivo attenuato",
        dataAutorizzazione: 2014.0,
        sviluppatori: "IL-CSM GmbH",
        patologiaDiInteresse: "Tifo, Salmonella Tiphi",
        calendarioVaccinale: "sopra i 5 anni che si recano in aree a rischio",
        obbligatorietà: "no",
        posologia: "1 dose con richiamo annuale se ci si reca nuovamente in aree a rischio",
        somministrazione: "orale"
    },
    {
        vaccineName: "DUKORAL",
        antigene: "ceppi di V. cholerae inattivati",
        baseTecnologicaVaccino: "vaccino inattivato ",
        dataAutorizzazione: 2004.0,
        sviluppatori: "Valneva Sweden AB",
        patologiaDiInteresse: "Colera, Vibrio Cholerae",
        calendarioVaccinale: "sopra i 2 anni che si recano in aree a richio",
        obbligatorietà: "no",
        posologia: "1 dose con richiamo ogni 3 anni se ci si reca nuovamente in aree a rischio",
        somministrazione: "orale"
    },
    {
        vaccineName: "IXIARO",
        antigene: "virus encefalite giapponese inattivato ",
        baseTecnologicaVaccino: "vaccino inattivato",
        dataAutorizzazione: 2009.0,
        sviluppatori: "Valneva Austria GmbH",
        patologiaDiInteresse: "Encefalite giapponese, Virus dell'Encefalite Giapponese (JEV)",
        calendarioVaccinale: "sopra i 2 mesi di età che si recano in aree a richio",
        obbligatorietà: "no",
        posologia: "2 dosi",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "RABIPUR",
        antigene: "virus della rabbia inattivato ",
        baseTecnologicaVaccino: "virus inattivato",
        dataAutorizzazione: 2008.0,
        sviluppatori: "GSK",
        patologiaDiInteresse: "Rabbia, Virus della rabbia",
        calendarioVaccinale: "qualsiasi età in condizioni di rischio esposizione",
        obbligatorietà: "no",
        posologia: "3 dosi in immunizzazione primaria.",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "TICOVAC",
        antigene: "vaccino encefalite da zecca purificato e inattivato",
        baseTecnologicaVaccino: "Virus inattivato",
        dataAutorizzazione: 0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "Virus della encefalite da zecca (TBE), encefalite",
        calendarioVaccinale: "a partire da 1 anno di età in persone esposte",
        obbligatorietà: "no",
        posologia: "3 dosi con primo richiamo a distanza di 3 anni e i successivi a 5",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "DENGVAXIA",
        antigene: "Virus Dengue attenuato",
        baseTecnologicaVaccino: "vivo attenuato",
        dataAutorizzazione: 2018.0,
        sviluppatori: "Sanofi",
        patologiaDiInteresse: "Dengue, Virus della Dengue",
        calendarioVaccinale: "dai 6 anni di età ai 45 anni ",
        obbligatorietà: "no",
        posologia: "3 dosi",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "FLUAD",
        antigene: "Virus influenzale inattivato",
        baseTecnologicaVaccino: "vaccino trivalente a subunità, inattivato",
        dataAutorizzazione: 0,
        sviluppatori: "Seqirus S.r.l.",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "persone fragili e over 64",
        obbligatorietà: "no",
        posologia: "1 dose annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "FLUARIX TETRA",
        antigene: "Virus influenzali frammentati e inattivati",
        baseTecnologicaVaccino: "Virus split frammentato inattivato",
        dataAutorizzazione: 0,
        sviluppatori: "GlaxoSmithKline Biologicals s.a. Rue de l’Institut",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "Dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "1 dose annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "FLUCELVAX TETRA",
        antigene: "Antigeni di superficie del virus dell’influenza (emoagglutinina\ne neuraminidasi), inattivati, derivati dai ceppi equivalenti.",
        baseTecnologicaVaccino: "Virus inattivati",
        dataAutorizzazione: 0,
        sviluppatori: "Seqirus Netherlands B.V.",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "Dai 2 anni di età",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "FLUENZ TETRA",
        antigene: "Virus dell’influenza ricombi0.",
        baseTecnologicaVaccino: "vivo attenuato",
        dataAutorizzazione: 2022.0,
        sviluppatori: "Astra Zeneca",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "Dai 24 mesi",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "spray nasale"
    },
    {
        vaccineName: "INFLUVAC S TETRA",
        antigene: "Antigene di superficie del virus influenzale, inattivato",
        baseTecnologicaVaccino: "Virus inattivato",
        dataAutorizzazione: 2022.0,
        sviluppatori: "Abbott Biologicals",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "PANDEMIC INFLUENZA VACCINE h4N1 ASTRAZENECA",
        antigene: "Virus dell’influenza ricombi0te",
        baseTecnologicaVaccino: "vivo attenuato",
        dataAutorizzazione: 2022.0,
        sviluppatori: "Astra Zeneca",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "dai 12 mesi di età",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "spray nasale"
    },
    {
        vaccineName: "PANDEMIC INFLUENZA VACCINE h4N1 BAXTER",
        antigene: "virus intero H5N1 per il vaccino dell'influenza, inattivato, contenente antigene",
        baseTecnologicaVaccino: "Virus inattivati",
        dataAutorizzazione: 2023.0,
        sviluppatori: "Baxster",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "VAXIGRIP TETRA",
        antigene: "Vaccino influenzale quadrivalente \n",
        baseTecnologicaVaccino: "Virus frammentati “split”, inattivati",
        dataAutorizzazione: 0,
        sviluppatori: "Sanofi",
        patologiaDiInteresse: "Virus influenzale, influenza",
        calendarioVaccinale: "dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "annuale",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "Comirnaty di Pfizer-BioNtech",
        antigene: "Vaccino a mRNA anti-COVID-19",
        baseTecnologicaVaccino: "Vaccino ad mRNA",
        dataAutorizzazione: 2020.0,
        sviluppatori: "Pfizer",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: "dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "3 dosi ",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "Spikevax (Moderna)",
        antigene: "Vaccino a mRNA anti-COVID-19",
        baseTecnologicaVaccino: "Vaccino ad mRNA",
        dataAutorizzazione: 2021.0,
        sviluppatori: "Moderna",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: "dai 6 mesi di età",
        obbligatorietà: "no",
        posologia: "3 dosi",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "Vaxzevria di AstraZeneca",
        antigene: "Vaccino anti-COVID-19",
        baseTecnologicaVaccino: "Vaccino a vettore virale adenovirus di scimpanzè covid-19",
        dataAutorizzazione: 2021.0,
        sviluppatori: "Astra Zeneca",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: "dai 18 anni",
        obbligatorietà: "no",
        posologia: "3 dosi",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "Janssen (Johnson & Johnson)",
        antigene: "Vaccino anti-COVID-19",
        baseTecnologicaVaccino: "Vaccino a vettore virale",
        dataAutorizzazione: 2021.0,
        sviluppatori: "Janssen",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: ">18 anni",
        obbligatorietà: "no",
        posologia: "1 dose",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "VidPrevtyn Beta (Sanofi)",
        antigene: "Vaccino adiuvato anti-Covid 19",
        baseTecnologicaVaccino: "Vaccino adiuvato composto dalla proteina trimerica solubile spike\nricombinante di SARS-CoV-2",
        dataAutorizzazione: 0,
        sviluppatori: "Sanofi",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: "Rivaccinazione dei soggetti >18 anni",
        obbligatorietà: "no",
        posologia: "utilizzato per le dosi di richiamo ",
        somministrazione: "intramuscolo"
    },
    {
        vaccineName: "Nuvaxovid (Novavax)",
        antigene: " Vaccino anti-COVID-19 ",
        baseTecnologicaVaccino: "Vaccino ricombi0te, adiuvato",
        dataAutorizzazione: 0,
        sviluppatori: "Novavax",
        patologiaDiInteresse: "Virus SARS-CoV2, malattia Covid",
        calendarioVaccinale: ">12 anni",
        obbligatorietà: "no",
        posologia: "6 mesi ",
        somministrazione: "intramuscolo"
    }
];
module.exports = vaccineData;